# Generated by Django 4.0 on 2024-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarapch', '0003_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='f', upload_to='media'),
            preserve_default=False,
        ),
    ]
